org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.daemon=true

android.useAndroidX=true
android.enableJetifier=true

# React Native architecture — New Architecture enabled
newArchEnabled=true

# Hermes JS engine (required for React Native 0.73+)
hermesEnabled=true

# Expo modules
expo.useLegacyPackaging=false
