ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS email_reminders     BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS streak_notifications BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS reminder_hour        SMALLINT NOT NULL DEFAULT 9
    CHECK (reminder_hour BETWEEN 0 AND 23);
